"""nakit akisi tablolari

Revision ID: 0c6388f1e72e
Revises: 82a42bb6f961
Create Date: 2026-08-14 20:56:17.210484

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0c6388f1e72e'
down_revision = '82a42bb6f961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nakit_plan',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('yon', sa.String(length=6), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('doviz', sa.String(length=5), nullable=True),
    sa.Column('aciklama', sa.String(length=200), nullable=True),
    sa.Column('kaynak', sa.String(length=20), nullable=True),
    sa.Column('kaynak_id', sa.String(length=20), nullable=True),
    sa.Column('cari_id', sa.String(length=20), nullable=True),
    sa.Column('gerceklesti', sa.Boolean(), nullable=True),
    sa.Column('gerceklesme_tarihi', sa.Date(), nullable=True),
    sa.Column('kullanici', sa.String(length=50), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nakit_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nakit_plan_tarih'), ['tarih'], unique=False)

    op.create_table('sabit_gider',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('tutar', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('doviz', sa.String(length=5), nullable=True),
    sa.Column('periyot', sa.String(length=10), nullable=True),
    sa.Column('ayin_gunu', sa.Integer(), nullable=True),
    sa.Column('haftanin_gunu', sa.Integer(), nullable=True),
    sa.Column('ay', sa.Integer(), nullable=True),
    sa.Column('baslangic', sa.Date(), nullable=True),
    sa.Column('bitis', sa.Date(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('olusturma', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sabit_gider')
    with op.batch_alter_table('nakit_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nakit_plan_tarih'))

    op.drop_table('nakit_plan')
    # ### end Alembic commands ###
