"""cari_tip 30 -> 120

Revision ID: 449ea44ca7c5
Revises: a98cf8f47990
Create Date: 2026-08-07 01:28:51.822380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449ea44ca7c5'
down_revision = 'a98cf8f47990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cariler', schema=None) as batch_op:
        batch_op.alter_column('cari_tip',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cariler', schema=None) as batch_op:
        batch_op.alter_column('cari_tip',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
