"""efektif_alis sutunu

Revision ID: 82a42bb6f961
Revises: 9901d1928d6b
Create Date: 2026-08-09 14:58:48.837776

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '82a42bb6f961'
down_revision = '9901d1928d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doviz_kur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('efektif_alis', sa.Numeric(precision=18, scale=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doviz_kur', schema=None) as batch_op:
        batch_op.drop_column('efektif_alis')

    # ### end Alembic commands ###
