"""kur_gerekce alani

Revision ID: 9901d1928d6b
Revises: 449ea44ca7c5
Create Date: 2026-08-09 08:02:48.211228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9901d1928d6b'
down_revision = '449ea44ca7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cari_hareket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kur_gerekce', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cari_hareket', schema=None) as batch_op:
        batch_op.drop_column('kur_gerekce')

    # ### end Alembic commands ###
