"""Float -> Numeric

Revision ID: a98cf8f47990
Revises: cf524082929d
Create Date: 2026-08-07 01:11:11.073271

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a98cf8f47990'
down_revision = 'cf524082929d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blok_stok', schema=None) as batch_op:
        batch_op.alter_column('boy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('en',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('hacim_m3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('tonaj',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('alis_fiyati',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kdv_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('matrah',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('cari_hareket', schema=None) as batch_op:
        batch_op.alter_column('borc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('alacak',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('kur_uygulanan',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
        batch_op.alter_column('borc_try',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('alacak_try',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('usd_kur',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
        batch_op.alter_column('eur_kur',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
        batch_op.alter_column('bakiye_try',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('bakiye_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('bakiye_eur',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kdv_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('matrah',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('cariler', schema=None) as batch_op:
        batch_op.alter_column('risk_limiti',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('cek', schema=None) as batch_op:
        batch_op.alter_column('tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('doviz_kur', schema=None) as batch_op:
        batch_op.alter_column('alis',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
        batch_op.alter_column('satis',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
        batch_op.alter_column('efektif',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)

    with op.batch_alter_table('ebatli_stok', schema=None) as batch_op:
        batch_op.alter_column('boy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kalinlik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('m2_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('metraj_m2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('metraj_sqft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('alis_fiyati',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kdv_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('matrah',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('faturalar', schema=None) as batch_op:
        batch_op.alter_column('toplam',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('ara_toplam',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kdv_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('tevkifat_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('alis_maliyeti',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('kasa', schema=None) as batch_op:
        batch_op.alter_column('bakiye',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('kasa_hareket', schema=None) as batch_op:
        batch_op.alter_column('tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('kdv_iade_dosya', schema=None) as batch_op:
        batch_op.alter_column('talep_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('onaylanan_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('alinan_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('kesim', schema=None) as batch_op:
        batch_op.alter_column('kaynak_miktar_once',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kaynak_miktar_sonra',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kaynak_birim_maliyet',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('kaynak_toplam_maliyet',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('fire_orani',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('fire_miktar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)

    with op.batch_alter_table('kesim_detay', schema=None) as batch_op:
        batch_op.alter_column('boy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kalinlik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('en',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('miktar_m2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('birim_maliyet',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('toplam_maliyet',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('konteyner', schema=None) as batch_op:
        batch_op.alter_column('tara_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('net_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('brut_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)

    with op.batch_alter_table('maliyetler', schema=None) as batch_op:
        batch_op.alter_column('tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('kur',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
        batch_op.alter_column('try_karsilik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('usd_karsilik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('eur_karsilik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('toplam_miktar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('birim_maliyet',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('plaka_stok', schema=None) as batch_op:
        batch_op.alter_column('boy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kalinlik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('m2_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('metraj_m2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('metraj_sqft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('alis_fiyati',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kdv_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('matrah',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.alter_column('birim_fiyat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('miktar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('toplam',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('iskonto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('iskonto_sabit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('avans_yuzdesi',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('avans_tutari',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('avans_sabit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)

    with op.batch_alter_table('proforma_kalem', schema=None) as batch_op:
        batch_op.alter_column('kalinlik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('en',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('boy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('miktar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('agirlik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('birim_fiyat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('toplam_fiyat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('net_fiyat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('iskonto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('iskonto_sabit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('avans_yuzdesi',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('avans_oran',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('m2_toplam',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('sqft_toplam',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)

    with op.batch_alter_table('rezervasyon', schema=None) as batch_op:
        batch_op.alter_column('miktar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)

    with op.batch_alter_table('satis_kaydi', schema=None) as batch_op:
        batch_op.alter_column('boy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kalinlik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('en',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('metraj_m2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('metraj_sqft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('hacim_m3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('tonaj',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('agirlik_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('birim_fiyat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('miktar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('kur_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
        batch_op.alter_column('kur_eur',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
        batch_op.alter_column('tutar_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('tutar_try',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('maliyet_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('maliyet_try',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('kar_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('marj_yuzde',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)

    with op.batch_alter_table('sevkiyat_kayit', schema=None) as batch_op:
        batch_op.alter_column('vgm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('navlun_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('siparis_kalem', schema=None) as batch_op:
        batch_op.alter_column('boy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('en',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kalinlik',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('miktar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('m2_toplam',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('m3_toplam',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('sqft_toplam',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kg_toplam',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('birim_fiyat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('toplam_fiyat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('siparis_kayit', schema=None) as batch_op:
        batch_op.alter_column('toplam_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=True)
        batch_op.alter_column('kdv_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('tevkifat_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('komisyon_deger',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('komisyon_tutar',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('stok_cikis', schema=None) as batch_op:
        batch_op.alter_column('alis_fiyati',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)
        batch_op.alter_column('satis_fiyati',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stok_cikis', schema=None) as batch_op:
        batch_op.alter_column('satis_fiyati',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('alis_fiyati',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('siparis_kayit', schema=None) as batch_op:
        batch_op.alter_column('komisyon_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('komisyon_deger',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('tevkifat_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kdv_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('toplam_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('siparis_kalem', schema=None) as batch_op:
        batch_op.alter_column('toplam_fiyat',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('birim_fiyat',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kg_toplam',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('sqft_toplam',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('m3_toplam',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('m2_toplam',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('miktar',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kalinlik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('en',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('boy',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('sevkiyat_kayit', schema=None) as batch_op:
        batch_op.alter_column('navlun_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('vgm',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('satis_kaydi', schema=None) as batch_op:
        batch_op.alter_column('marj_yuzde',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kar_usd',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('maliyet_try',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('maliyet_usd',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('tutar_try',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('tutar_usd',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kur_eur',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kur_usd',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('miktar',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('birim_fiyat',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('agirlik_kg',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('tonaj',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('hacim_m3',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('metraj_sqft',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('metraj_m2',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('en',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kalinlik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('boy',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('rezervasyon', schema=None) as batch_op:
        batch_op.alter_column('miktar',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('proforma_kalem', schema=None) as batch_op:
        batch_op.alter_column('sqft_toplam',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('m2_toplam',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('avans_oran',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('avans_yuzdesi',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('iskonto_sabit',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('iskonto',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('net_fiyat',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('toplam_fiyat',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('birim_fiyat',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('agirlik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('miktar',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('boy',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('en',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kalinlik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('proforma', schema=None) as batch_op:
        batch_op.alter_column('kdv_oran',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('avans_sabit',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('avans_tutari',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('avans_yuzdesi',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('iskonto_sabit',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('iskonto',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('toplam',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('miktar',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('birim_fiyat',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('plaka_stok', schema=None) as batch_op:
        batch_op.alter_column('matrah',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kdv_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('alis_fiyati',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('metraj_sqft',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('metraj_m2',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('m2_kg',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kalinlik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('boy',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('maliyetler', schema=None) as batch_op:
        batch_op.alter_column('birim_maliyet',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('toplam_miktar',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('eur_karsilik',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('usd_karsilik',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('try_karsilik',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kur',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('konteyner', schema=None) as batch_op:
        batch_op.alter_column('brut_kg',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('net_kg',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('tara_kg',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('kesim_detay', schema=None) as batch_op:
        batch_op.alter_column('toplam_maliyet',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('birim_maliyet',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('miktar_m2',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('en',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kalinlik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('boy',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('kesim', schema=None) as batch_op:
        batch_op.alter_column('fire_miktar',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('fire_orani',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kaynak_toplam_maliyet',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kaynak_birim_maliyet',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kaynak_miktar_sonra',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kaynak_miktar_once',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('kdv_iade_dosya', schema=None) as batch_op:
        batch_op.alter_column('alinan_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('onaylanan_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('talep_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('kasa_hareket', schema=None) as batch_op:
        batch_op.alter_column('tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('kasa', schema=None) as batch_op:
        batch_op.alter_column('bakiye',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('faturalar', schema=None) as batch_op:
        batch_op.alter_column('alis_maliyeti',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('tevkifat_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kdv_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('ara_toplam',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('toplam',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('ebatli_stok', schema=None) as batch_op:
        batch_op.alter_column('matrah',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kdv_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('alis_fiyati',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('metraj_sqft',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('metraj_m2',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('m2_kg',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kalinlik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('boy',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('doviz_kur', schema=None) as batch_op:
        batch_op.alter_column('efektif',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('satis',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('alis',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('cek', schema=None) as batch_op:
        batch_op.alter_column('tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('cariler', schema=None) as batch_op:
        batch_op.alter_column('risk_limiti',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('cari_hareket', schema=None) as batch_op:
        batch_op.alter_column('matrah',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kdv_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('bakiye_eur',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('bakiye_usd',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('bakiye_try',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('eur_kur',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('usd_kur',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('alacak_try',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('borc_try',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kur_uygulanan',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('alacak',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('borc',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('blok_stok', schema=None) as batch_op:
        batch_op.alter_column('matrah',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kdv_tutar',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('kdv_oran',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('alis_fiyati',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('tonaj',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('hacim_m3',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('en',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('yukseklik',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('boy',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
